web_app/adverts/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class OlxSite(db.Model):
    __tablename__ = 'olx_site'
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String, unique=True, nullable=True)
    origin_id = db.Column(db.String, unique=True, nullable=True)
    category = db.Column(db.String)
    ads_name = db.Column(db.String)
    ads_content = db.Column(db.Text)
    phone_number = db.Column(db.String)
    seller_name = db.Column(db.String)
    date_registered = db.Column(db.DateTime, nullable=True)
    date_of_last_visit = db.Column(db.DateTime, nullable=True)
    date_posted = db.Column(db.DateTime, nullable=True)
    number_of_views = db.Column(db.Integer)
    location = db.Column(db.String)
    picture_url = db.Column(db.String)

    def __repr__(self):
        return f'<Ads {self.name} {self.content}>'

web_app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class OlxSite(db.Model):
    __tablename__ = 'olx_site'
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String, unique=True, nullable=True)
    origin_id = db.Column(db.String, unique=True, nullable=True)
    category = db.Column(db.String)
    ads_name = db.Column(db.String)
    ads_content = db.Column(db.Text)
    phone_number = db.Column(db.String)
    seller_name = db.Column(db.String)
    date_registered = db.Column(db.DateTime, nullable=True)
    date_of_last_visit = db.Column(db.DateTime, nullable=True)
    date_posted = db.Column(db.DateTime, nullable=True)
    number_of_views = db.Column(db.Integer)
    location = db.Column(db.String)
    picture_url = db.Column(db.String)

    def __repr__(self):
        return f'<Ads {self.name} {self.content}>'

web_app/user/models.py
from flask_login import UserMixin
from web_app.adverts.models import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_migrate import Migrate

migrate = Migrate(db)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(500))
    role = db.Column(db.String(10), index=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return '<User {}>'.format(self.username)

web_app/user/forms.py
from flask_wtf import FlaskForm

from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()],
                           render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()],
                             render_kw={"class": "form-control"})
    submit = SubmitField('Отправить', render_kw={"class": "btn btn-primary"})

web_app/__init__.py
from flask import Flask
from web_app.models import db, OlxSite
from flask import render_template
from flask_migrate import Migrate
from web_app.database_functions import extract_from_db


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    with app.app_context():
        db.create_all()
    migrate = Migrate(app, db, command='migrate')

    @app.route('/')
    def index():
        ads_list = extract_from_db() # order_by(OlxSite.date_posted.desc())
        return render_template('index.html', ads_list=ads_list)
    return app
      


    
            

web_app/adverts/views.py
from flask import Blueprint, request, render_template

from web_app.database_functions import extract_from_db

blueprint = Blueprint('adverts', __name__)


@blueprint.route('/adverts')
def adverts():
    ads_list = extract_from_db()
    page = request.args.get('page', 1, type=int)
    pagination = ads_list.paginate(page=page, per_page=5)

    return render_template('adverts.html', pagination=pagination)

web_app/app.py
from flask import Flask
from web_app.adverts.models import db
from flask import render_template
from flask_migrate import Migrate

from web_app.adverts.views import blueprint as adverts_blueprint
from web_app.user.views import blueprint as user_blueprint
from web_app.user.models import User
from flask_login import LoginManager


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    app.register_blueprint(adverts_blueprint)
    with app.app_context():
        db.create_all()
        app.register_blueprint(user_blueprint)
    migrate = Migrate(app, db, command='migrate')

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    @app.route('/')
    def main():
        return render_template('main.html')

    return app

web_app/user/views.py
from flask import Blueprint
from flask import render_template, flash, redirect, url_for
from web_app.user.forms import LoginForm
from web_app.user.models import User
from flask_login import current_user, login_required, login_user, logout_user
from web_app.user.models import db

blueprint = Blueprint('user', __name__)


@blueprint.route('/register', methods=["GET", "POST"])
def register_page():
    form = LoginForm()
    if form.validate():
        username = form.username.data
        password = form.password.data
        new_user = User(username=username)
        new_user.set_password(password)

        if User.query.filter(User.username == username).count():
            flash('Такой пользователь уже есть')
            return redirect(url_for('register'))
        else:
            db.session.add(new_user)
            db.session.commit()
            flash("Thanks for registering!")
            return redirect(url_for('adverts'))
    title = "Регистрация"
    return render_template("registration.html", page_title=title,
                           form=form)


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main'))
    title = "Авторизация"

    login_form = LoginForm()
    return render_template('login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['GET', 'POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Вы вошли на сайт')
            return redirect(url_for('adverts'))
    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@blueprint.route('/admin')
@login_required
def admin_index():
    if current_user.is_admin:
        return 'Привет админ'
    else:
        return 'Ты не админ!'

web_app/templates/adverts.html
{% extends 'base.html' %}

{% block title %}
OLX-Клон
{% endblock %}


 {% block body %}

    <h1>
        Сайт объявлений
    </h1>
    <div class= 'row'>
        <div class= "col-8">
            <h2> Объявления </h2>
            <h4>(Page {{ pagination.page }})</h4>
            {% for ad in pagination.items %}
            <h3> <a href = "{{ ad.url }}">{{ ad.ads_name }} </a>  </h3>
            <p>{{ ad.ads_content}}</p>
            <p>{{ ad.phone_number}}</p>
            <p>{{ ad.seller_name}}</p>
            <p>{{ ad.date_registered.strftime('%Y-%m-%d')}}</p>
            <p>{{ ad.date_posted.strftime('%Y-%m-%d') }}</p>
            <p>{{ ad.date_of_last_visit.strftime('%Y-%m-%d') }}</p>
            <p>{{ ad.number_of_looks }}</p>
            <p>{{ ad.location}}</p>
            <p>{{ ad.category}}</p>
            <img src ="{{ ad.picture_url }}" alt ="no picture today, sorry" >
            {% endfor %}
        </div>
        </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>


<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
     {% for page_num in pagination.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
       {% if page_num %}
           {% if pagination.page==page_num %}
               <li class='page-item disabled'>
               <a class="page-link" href="{{ url_for('adverts.adverts', page=page_num)}}">{{ page_num }}</a>
               </li>
           {% else %}
               <li class='page-item'>
               <a class="page-link" href="{{ url_for('adverts.adverts', page=page_num)}}">{{ page_num }}</a>
               </li>
           {% endif %}

       {% endif %}
     {% endfor %}
   </ul>
</nav>

{% endblock %}

web_app/templates/base.html
<!doctype html>
<html lang="ru">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
    
      .title {
          margin: 5px;
          position: absolute;
      }

      .content {
          margin: 5px;
          width: 100%;

          display: flex;
          flex-direction: row;
          flex-wrap: wrap;
      }


      .pagination {
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .pagination__arrow_prev {
        position: relative;
        cursor: pointer;
      }

      .pagination__arrow_prev::before {
        content: "";
        position: absolute;
        top: -15px;
        left: -50px;
        height: 0;
        width: 0;
        border-width: 15px 30px 15px 0;
        border-color: transparent rgba(0, 0, 0, 0.55) transparent transparent;
        border-style: solid;
        filter: drop-shadow(10px 0px 5px rgba(0, 0, 0, 0.55));
      }

      .pagination__arrow_next {
        position: relative;
        cursor: pointer;
      }

      .pagination__arrow_next::before {
        position: absolute;
        content: "";
        top: -15px;
        right: -50px;
        width: 0;
        height: 0;
        border-width: 15px 0 15px 30px;
        border-color: transparent transparent transparent rgba(0, 0, 0, 0.55);
        border-style: solid;
        filter: drop-shadow(-10px 0px 5px rgba(0, 0, 0, 0.55));
      }

      .pagination__list {
        list-style: none;
        display: flex;
        gap: 0 20px;
        padding: 0;
      }

      .pagination__item {
        border: 1px solid rgba(0, 0, 0, 0.55);
        border-radius: 22px;
        box-shadow: 0 0 10px 5px rgba(0, 0, 0, 0.55);
      }

      ._hide {
        position: relative;
        border: 1px solid rgba(0, 0, 0, 0);
        box-shadow: 0 0 10px 5px rgba(0, 0, 0, 0);
      }
      ._hide::after {
        content: "• • •";
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        display: grid;
        place-items: center;
        border-radius: 22px;
        background-color: #fff;
      }
      ._hide+._hide {
        display: none;
      }

      .pagination__item span {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 40px;
        height: 40px;
        border-radius: 22px;
        cursor: pointer;
      }

      .pagination__item span._active {
        box-shadow: 0 0 10px 5px rgba(255, 0, 0, 0.55);
      }

      .pagination__link {
        font-size: 20px;
        color: #3b3b3b;
      }
.dropbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px;
        font-size: 16px;
        border: none;
        bottom: - 10%;
    }
    
    .dropup {
        position:relative;
        display: inline-block;
    }
    
    .dropup-content {
        display: none;
        position: absolute;
        background-color: #f1f1f1;
        min-width: 160px;
        bottom: 50px;
        z-index: 1;
    }
    
    .dropup-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
    }
    
    .dropup-content a:hover {background-color: #ccc}
    
    .dropup:hover .dropup-content {
        display: block;
    }
    
    .dropup:hover .dropbtn {
        background-color: #3e8e41;
    }
  </style>
</head>
<body>
{% block body %}{% endblock %}
        
 <nav class="navbar navbar-expand-md navbar-dark fixed-bottom bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Главная страница</a>
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse" id="navbarCollapse" style="">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="/register">Регистрация</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Вход</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/logout">Выход</a>
          </li>
         <li class="nav-item">
            <a class="nav-link" href="/adverts">Объявления</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
          <button class="btn btn-outline-success" type="submit">Поиск</button>
        </form>
      </div>
    </div>
  </nav>
</body>
</html>

web_app/templates/login.html
{% extends "base.html" %}
{% block title %}
Авторизация
{% endblock %}
{% block body %}
<h1>Вход</h1>
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}
<div class= "col-4">
<form action="{{ url_for('user.process_login') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}
        {{ form.username() }}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password() }}
    </div>
    {{ form.submit }}
</form>
<div class= "col-8">
</div>
</div>
{% endblock %}

web_app/templates/main.html
{% extends 'base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block body %}
<h1>Главная страница</h1>
{% endblock %}

web_app/templates/registration.html
{% extends "base.html" %}

{% block title %}
Регистрация
{% endblock %}
{% block body %}
<h1>Регистрация</h1>
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}
<div class= "col-4">
    <form action="{{ url_for('user.register_page') }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.username.label }}
            {{ form.username() }}
        </div>
        <div class="form-group">
            {{ form.password.label }}
            {{ form.password() }}
        </div>
        {{ form.submit }}
    </form>
<div class= "col-4">
</div>
</div>
{% endblock %}

web_app/templates/user/login.html
{% extends "base.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}
<form action="{{ url_for('user.process_login') }}" method="post">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}<br>
        {{ form.username() }}
    </div>
    <div class="form-group">
        {{ form.password.label }}<br>
        {{ form.password() }}
    </div>
    {{ form.submit }}
</form>
{% endblock %}